import * as Css from "../css";

export type CssPercentage = Css.Numeric & { unit: "%" };

export const CssNumber = Css.Num;
export type CssNumber = Css.Num;

/**
 * @see https://www.w3.org/TR/2024/WD-css-values-4-20240312/
 */
export type CssAngle = Css.Numeric & { unit: "deg" | "grad" | "rad" | "turn" };

export type DashedIdent = Css.Ident & { name: `--${string}` };

export type CssIdentNone = Css.Ident & { name: "none" };
export function isIdentNone(value: unknown): value is CssIdentNone {
  return value instanceof Css.Ident && value.name === "none";
}

// https://www.w3.org/TR/2026/CRD-css-color-4-20260331/#valdef-color-currentcolor
export type CssIdentCurrentcolor = Css.Ident & { name: "currentcolor" };

// https://www.w3.org/TR/2026/CRD-css-color-4-20260331/#valdef-color-transparent
export type CssIdentTransparent = Css.Ident & { name: "transparent" };

// https://www.w3.org/TR/2026/CRD-css-color-4-20260331/#typedef-system-color
export type CssIdentAccentColor = Css.Ident & { name: "AccentColor" };
export type CssIdentAccentColorText = Css.Ident & { name: "AccentColorText" };
export type CssIdentActiveText = Css.Ident & { name: "ActiveText" };
export type CssIdentButtonBorder = Css.Ident & { name: "ButtonBorder" };
export type CssIdentButtonFace = Css.Ident & { name: "ButtonFace" };
export type CssIdentButtonText = Css.Ident & { name: "ButtonText" };
export type CssIdentCanvas = Css.Ident & { name: "Canvas" };
export type CssIdentCanvasText = Css.Ident & { name: "CanvasText" };
export type CssIdentField = Css.Ident & { name: "Field" };
export type CssIdentFieldText = Css.Ident & { name: "FieldText" };
export type CssIdentGrayText = Css.Ident & { name: "GrayText" };
export type CssIdentHighlight = Css.Ident & { name: "Highlight" };
export type CssIdentHighlightText = Css.Ident & { name: "HighlightText" };
export type CssIdentLinkText = Css.Ident & { name: "LinkText" };
export type CssIdentMark = Css.Ident & { name: "Mark" };
export type CssIdentMarkText = Css.Ident & { name: "MarkText" };
export type CssIdentSelectedItem = Css.Ident & { name: "SelectedItem" };
export type CssIdentSelectedItemText = Css.Ident & { name: "SelectedItemText" };
export type CssIdentVisitedText = Css.Ident & { name: "VisitedText" };

// https://www.w3.org/TR/2026/WD-css-color-5-20260325/#typedef-predefined-rgb
export type CssIdentSrgb = Css.Ident & { name: "srgb" };
export type CssIdentSrgbLinear = Css.Ident & { name: "srgb-linear" };
export type CssIdentDisplayP3 = Css.Ident & { name: "display-p3" };
export type CssIdentA98Rgb = Css.Ident & { name: "a98-rgb" };
export type CssIdentProphotoRgb = Css.Ident & { name: "prophoto-rgb" };
export type CssIdentRec2020 = Css.Ident & { name: "rec2020" };

// https://www.w3.org/TR/2026/CRD-css-color-4-20260331/#typedef-xyz-space
export type CssIdentXyz = Css.Ident & { name: "xyz" };
export type CssIdentXyzD50 = Css.Ident & { name: "xyz-d50" };
export type CssIdentXyzD65 = Css.Ident & { name: "xyz-d65" };

// https://www.w3.org/TR/2026/CRD-css-color-4-20260331/#typedef-named-color
export type CssIdentAliceblue = Css.Ident & { name: "aliceblue" };
export type CssIdentAntiquewhite = Css.Ident & { name: "antiquewhite" };
export type CssIdentAqua = Css.Ident & { name: "aqua" };
export type CssIdentAquamarine = Css.Ident & { name: "aquamarine" };
export type CssIdentAzure = Css.Ident & { name: "azure" };
export type CssIdentBeige = Css.Ident & { name: "beige" };
export type CssIdentBisque = Css.Ident & { name: "bisque" };
export type CssIdentBlack = Css.Ident & { name: "black" };
export type CssIdentBlanchedalmond = Css.Ident & { name: "blanchedalmond" };
export type CssIdentBlue = Css.Ident & { name: "blue" };
export type CssIdentBlueviolet = Css.Ident & { name: "blueviolet" };
export type CssIdentBrown = Css.Ident & { name: "brown" };
export type CssIdentBurlywood = Css.Ident & { name: "burlywood" };
export type CssIdentCadetblue = Css.Ident & { name: "cadetblue" };
export type CssIdentChartreuse = Css.Ident & { name: "chartreuse" };
export type CssIdentChocolate = Css.Ident & { name: "chocolate" };
export type CssIdentCoral = Css.Ident & { name: "coral" };
export type CssIdentCornflowerblue = Css.Ident & { name: "cornflowerblue" };
export type CssIdentCornsilk = Css.Ident & { name: "cornsilk" };
export type CssIdentCrimson = Css.Ident & { name: "crimson" };
export type CssIdentCyan = Css.Ident & { name: "cyan" };
export type CssIdentDarkblue = Css.Ident & { name: "darkblue" };
export type CssIdentDarkcyan = Css.Ident & { name: "darkcyan" };
export type CssIdentDarkgoldenrod = Css.Ident & { name: "darkgoldenrod" };
export type CssIdentDarkgray = Css.Ident & { name: "darkgray" };
export type CssIdentDarkgreen = Css.Ident & { name: "darkgreen" };
export type CssIdentDarkgrey = Css.Ident & { name: "darkgrey" };
export type CssIdentDarkkhaki = Css.Ident & { name: "darkkhaki" };
export type CssIdentDarkmagenta = Css.Ident & { name: "darkmagenta" };
export type CssIdentDarkolivegreen = Css.Ident & { name: "darkolivegreen" };
export type CssIdentDarkorange = Css.Ident & { name: "darkorange" };
export type CssIdentDarkorchid = Css.Ident & { name: "darkorchid" };
export type CssIdentDarkred = Css.Ident & { name: "darkred" };
export type CssIdentDarksalmon = Css.Ident & { name: "darksalmon" };
export type CssIdentDarkseagreen = Css.Ident & { name: "darkseagreen" };
export type CssIdentDarkslateblue = Css.Ident & { name: "darkslateblue" };
export type CssIdentDarkslategray = Css.Ident & { name: "darkslategray" };
export type CssIdentDarkslategrey = Css.Ident & { name: "darkslategrey" };
export type CssIdentDarkturquoise = Css.Ident & { name: "darkturquoise" };
export type CssIdentDarkviolet = Css.Ident & { name: "darkviolet" };
export type CssIdentDeeppink = Css.Ident & { name: "deeppink" };
export type CssIdentDeepskyblue = Css.Ident & { name: "deepskyblue" };
export type CssIdentDimgray = Css.Ident & { name: "dimgray" };
export type CssIdentDimgrey = Css.Ident & { name: "dimgrey" };
export type CssIdentDodgerblue = Css.Ident & { name: "dodgerblue" };
export type CssIdentFirebrick = Css.Ident & { name: "firebrick" };
export type CssIdentFloralwhite = Css.Ident & { name: "floralwhite" };
export type CssIdentForestgreen = Css.Ident & { name: "forestgreen" };
export type CssIdentFuchsia = Css.Ident & { name: "fuchsia" };
export type CssIdentGainsboro = Css.Ident & { name: "gainsboro" };
export type CssIdentGhostwhite = Css.Ident & { name: "ghostwhite" };
export type CssIdentGold = Css.Ident & { name: "gold" };
export type CssIdentGoldenrod = Css.Ident & { name: "goldenrod" };
export type CssIdentGray = Css.Ident & { name: "gray" };
export type CssIdentGreen = Css.Ident & { name: "green" };
export type CssIdentGreenyellow = Css.Ident & { name: "greenyellow" };
export type CssIdentGrey = Css.Ident & { name: "grey" };
export type CssIdentHoneydew = Css.Ident & { name: "honeydew" };
export type CssIdentHotpink = Css.Ident & { name: "hotpink" };
export type CssIdentIndianred = Css.Ident & { name: "indianred" };
export type CssIdentIndigo = Css.Ident & { name: "indigo" };
export type CssIdentIvory = Css.Ident & { name: "ivory" };
export type CssIdentKhaki = Css.Ident & { name: "khaki" };
export type CssIdentLavender = Css.Ident & { name: "lavender" };
export type CssIdentLavenderblush = Css.Ident & { name: "lavenderblush" };
export type CssIdentLawngreen = Css.Ident & { name: "lawngreen" };
export type CssIdentLemonchiffon = Css.Ident & { name: "lemonchiffon" };
export type CssIdentLightblue = Css.Ident & { name: "lightblue" };
export type CssIdentLightcoral = Css.Ident & { name: "lightcoral" };
export type CssIdentLightcyan = Css.Ident & { name: "lightcyan" };
export type CssIdentLightgoldenrodyellow = Css.Ident & {
  name: "lightgoldenrodyellow";
};
export type CssIdentLightgray = Css.Ident & { name: "lightgray" };
export type CssIdentLightgreen = Css.Ident & { name: "lightgreen" };
export type CssIdentLightgrey = Css.Ident & { name: "lightgrey" };
export type CssIdentLightpink = Css.Ident & { name: "lightpink" };
export type CssIdentLightsalmon = Css.Ident & { name: "lightsalmon" };
export type CssIdentLightseagreen = Css.Ident & { name: "lightseagreen" };
export type CssIdentLightskyblue = Css.Ident & { name: "lightskyblue" };
export type CssIdentLightslategray = Css.Ident & { name: "lightslategray" };
export type CssIdentLightslategrey = Css.Ident & { name: "lightslategrey" };
export type CssIdentLightsteelblue = Css.Ident & { name: "lightsteelblue" };
export type CssIdentLightyellow = Css.Ident & { name: "lightyellow" };
export type CssIdentLime = Css.Ident & { name: "lime" };
export type CssIdentLimegreen = Css.Ident & { name: "limegreen" };
export type CssIdentLinen = Css.Ident & { name: "linen" };
export type CssIdentMagenta = Css.Ident & { name: "magenta" };
export type CssIdentMaroon = Css.Ident & { name: "maroon" };
export type CssIdentMediumaquamarine = Css.Ident & { name: "mediumaquamarine" };
export type CssIdentMediumblue = Css.Ident & { name: "mediumblue" };
export type CssIdentMediumorchid = Css.Ident & { name: "mediumorchid" };
export type CssIdentMediumpurple = Css.Ident & { name: "mediumpurple" };
export type CssIdentMediumseagreen = Css.Ident & { name: "mediumseagreen" };
export type CssIdentMediumslateblue = Css.Ident & { name: "mediumslateblue" };
export type CssIdentMediumspringgreen = Css.Ident & {
  name: "mediumspringgreen";
};
export type CssIdentMediumturquoise = Css.Ident & { name: "mediumturquoise" };
export type CssIdentMediumvioletred = Css.Ident & { name: "mediumvioletred" };
export type CssIdentMidnightblue = Css.Ident & { name: "midnightblue" };
export type CssIdentMintcream = Css.Ident & { name: "mintcream" };
export type CssIdentMistyrose = Css.Ident & { name: "mistyrose" };
export type CssIdentMoccasin = Css.Ident & { name: "moccasin" };
export type CssIdentNavajowhite = Css.Ident & { name: "navajowhite" };
export type CssIdentNavy = Css.Ident & { name: "navy" };
export type CssIdentOldlace = Css.Ident & { name: "oldlace" };
export type CssIdentOlive = Css.Ident & { name: "olive" };
export type CssIdentOlivedrab = Css.Ident & { name: "olivedrab" };
export type CssIdentOrange = Css.Ident & { name: "orange" };
export type CssIdentOrangered = Css.Ident & { name: "orangered" };
export type CssIdentOrchid = Css.Ident & { name: "orchid" };
export type CssIdentPalegoldenrod = Css.Ident & { name: "palegoldenrod" };
export type CssIdentPalegreen = Css.Ident & { name: "palegreen" };
export type CssIdentPaleturquoise = Css.Ident & { name: "paleturquoise" };
export type CssIdentPalevioletred = Css.Ident & { name: "palevioletred" };
export type CssIdentPapayawhip = Css.Ident & { name: "papayawhip" };
export type CssIdentPeachpuff = Css.Ident & { name: "peachpuff" };
export type CssIdentPeru = Css.Ident & { name: "peru" };
export type CssIdentPink = Css.Ident & { name: "pink" };
export type CssIdentPlum = Css.Ident & { name: "plum" };
export type CssIdentPowderblue = Css.Ident & { name: "powderblue" };
export type CssIdentPurple = Css.Ident & { name: "purple" };
export type CssIdentRebeccapurple = Css.Ident & { name: "rebeccapurple" };
export type CssIdentRed = Css.Ident & { name: "red" };
export type CssIdentRosybrown = Css.Ident & { name: "rosybrown" };
export type CssIdentRoyalblue = Css.Ident & { name: "royalblue" };
export type CssIdentSaddlebrown = Css.Ident & { name: "saddlebrown" };
export type CssIdentSalmon = Css.Ident & { name: "salmon" };
export type CssIdentSandybrown = Css.Ident & { name: "sandybrown" };
export type CssIdentSeagreen = Css.Ident & { name: "seagreen" };
export type CssIdentSeashell = Css.Ident & { name: "seashell" };
export type CssIdentSienna = Css.Ident & { name: "sienna" };
export type CssIdentSilver = Css.Ident & { name: "silver" };
export type CssIdentSkyblue = Css.Ident & { name: "skyblue" };
export type CssIdentSlateblue = Css.Ident & { name: "slateblue" };
export type CssIdentSlategray = Css.Ident & { name: "slategray" };
export type CssIdentSlategrey = Css.Ident & { name: "slategrey" };
export type CssIdentSnow = Css.Ident & { name: "snow" };
export type CssIdentSpringgreen = Css.Ident & { name: "springgreen" };
export type CssIdentSteelblue = Css.Ident & { name: "steelblue" };
export type CssIdentTan = Css.Ident & { name: "tan" };
export type CssIdentTeal = Css.Ident & { name: "teal" };
export type CssIdentThistle = Css.Ident & { name: "thistle" };
export type CssIdentTomato = Css.Ident & { name: "tomato" };
export type CssIdentTurquoise = Css.Ident & { name: "turquoise" };
export type CssIdentViolet = Css.Ident & { name: "violet" };
export type CssIdentWheat = Css.Ident & { name: "wheat" };
export type CssIdentWhite = Css.Ident & { name: "white" };
export type CssIdentWhitesmoke = Css.Ident & { name: "whitesmoke" };
export type CssIdentYellow = Css.Ident & { name: "yellow" };
export type CssIdentYellowgreen = Css.Ident & { name: "yellowgreen" };

declare module "../css" {
  export function getName(name: "none"): CssIdentNone;
  export function getName(name: "currentcolor"): CssIdentCurrentcolor;
  export function getName(name: "transparent"): CssIdentTransparent;
  export function getName(name: "AccentColor"): CssIdentAccentColor;
  export function getName(name: "AccentColorText"): CssIdentAccentColorText;
  export function getName(name: "ActiveText"): CssIdentActiveText;
  export function getName(name: "ButtonBorder"): CssIdentButtonBorder;
  export function getName(name: "ButtonFace"): CssIdentButtonFace;
  export function getName(name: "ButtonText"): CssIdentButtonText;
  export function getName(name: "Canvas"): CssIdentCanvas;
  export function getName(name: "CanvasText"): CssIdentCanvasText;
  export function getName(name: "Field"): CssIdentField;
  export function getName(name: "FieldText"): CssIdentFieldText;
  export function getName(name: "GrayText"): CssIdentGrayText;
  export function getName(name: "Highlight"): CssIdentHighlight;
  export function getName(name: "HighlightText"): CssIdentHighlightText;
  export function getName(name: "LinkText"): CssIdentLinkText;
  export function getName(name: "Mark"): CssIdentMark;
  export function getName(name: "MarkText"): CssIdentMarkText;
  export function getName(name: "SelectedItem"): CssIdentSelectedItem;
  export function getName(name: "SelectedItemText"): CssIdentSelectedItemText;
  export function getName(name: "VisitedText"): CssIdentVisitedText;
  export function getName(name: "srgb"): CssIdentSrgb;
  export function getName(name: "srgb-linear"): CssIdentSrgbLinear;
  export function getName(name: "display-p3"): CssIdentDisplayP3;
  export function getName(name: "a98-rgb"): CssIdentA98Rgb;
  export function getName(name: "prophoto-rgb"): CssIdentProphotoRgb;
  export function getName(name: "rec2020"): CssIdentRec2020;
  export function getName(name: "xyz"): CssIdentXyz;
  export function getName(name: "xyz-d50"): CssIdentXyzD50;
  export function getName(name: "xyz-d65"): CssIdentXyzD65;
  export function getName(name: "aliceblue"): CssIdentAliceblue;
  export function getName(name: "antiquewhite"): CssIdentAntiquewhite;
  export function getName(name: "aqua"): CssIdentAqua;
  export function getName(name: "aquamarine"): CssIdentAquamarine;
  export function getName(name: "azure"): CssIdentAzure;
  export function getName(name: "beige"): CssIdentBeige;
  export function getName(name: "bisque"): CssIdentBisque;
  export function getName(name: "black"): CssIdentBlack;
  export function getName(name: "blanchedalmond"): CssIdentBlanchedalmond;
  export function getName(name: "blue"): CssIdentBlue;
  export function getName(name: "blueviolet"): CssIdentBlueviolet;
  export function getName(name: "brown"): CssIdentBrown;
  export function getName(name: "burlywood"): CssIdentBurlywood;
  export function getName(name: "cadetblue"): CssIdentCadetblue;
  export function getName(name: "chartreuse"): CssIdentChartreuse;
  export function getName(name: "chocolate"): CssIdentChocolate;
  export function getName(name: "coral"): CssIdentCoral;
  export function getName(name: "cornflowerblue"): CssIdentCornflowerblue;
  export function getName(name: "cornsilk"): CssIdentCornsilk;
  export function getName(name: "crimson"): CssIdentCrimson;
  export function getName(name: "cyan"): CssIdentCyan;
  export function getName(name: "darkblue"): CssIdentDarkblue;
  export function getName(name: "darkcyan"): CssIdentDarkcyan;
  export function getName(name: "darkgoldenrod"): CssIdentDarkgoldenrod;
  export function getName(name: "darkgray"): CssIdentDarkgray;
  export function getName(name: "darkgreen"): CssIdentDarkgreen;
  export function getName(name: "darkgrey"): CssIdentDarkgrey;
  export function getName(name: "darkkhaki"): CssIdentDarkkhaki;
  export function getName(name: "darkmagenta"): CssIdentDarkmagenta;
  export function getName(name: "darkolivegreen"): CssIdentDarkolivegreen;
  export function getName(name: "darkorange"): CssIdentDarkorange;
  export function getName(name: "darkorchid"): CssIdentDarkorchid;
  export function getName(name: "darkred"): CssIdentDarkred;
  export function getName(name: "darksalmon"): CssIdentDarksalmon;
  export function getName(name: "darkseagreen"): CssIdentDarkseagreen;
  export function getName(name: "darkslateblue"): CssIdentDarkslateblue;
  export function getName(name: "darkslategray"): CssIdentDarkslategray;
  export function getName(name: "darkslategrey"): CssIdentDarkslategrey;
  export function getName(name: "darkturquoise"): CssIdentDarkturquoise;
  export function getName(name: "darkviolet"): CssIdentDarkviolet;
  export function getName(name: "deeppink"): CssIdentDeeppink;
  export function getName(name: "deepskyblue"): CssIdentDeepskyblue;
  export function getName(name: "dimgray"): CssIdentDimgray;
  export function getName(name: "dimgrey"): CssIdentDimgrey;
  export function getName(name: "dodgerblue"): CssIdentDodgerblue;
  export function getName(name: "firebrick"): CssIdentFirebrick;
  export function getName(name: "floralwhite"): CssIdentFloralwhite;
  export function getName(name: "forestgreen"): CssIdentForestgreen;
  export function getName(name: "fuchsia"): CssIdentFuchsia;
  export function getName(name: "gainsboro"): CssIdentGainsboro;
  export function getName(name: "ghostwhite"): CssIdentGhostwhite;
  export function getName(name: "gold"): CssIdentGold;
  export function getName(name: "goldenrod"): CssIdentGoldenrod;
  export function getName(name: "gray"): CssIdentGray;
  export function getName(name: "green"): CssIdentGreen;
  export function getName(name: "greenyellow"): CssIdentGreenyellow;
  export function getName(name: "grey"): CssIdentGrey;
  export function getName(name: "honeydew"): CssIdentHoneydew;
  export function getName(name: "hotpink"): CssIdentHotpink;
  export function getName(name: "indianred"): CssIdentIndianred;
  export function getName(name: "indigo"): CssIdentIndigo;
  export function getName(name: "ivory"): CssIdentIvory;
  export function getName(name: "khaki"): CssIdentKhaki;
  export function getName(name: "lavender"): CssIdentLavender;
  export function getName(name: "lavenderblush"): CssIdentLavenderblush;
  export function getName(name: "lawngreen"): CssIdentLawngreen;
  export function getName(name: "lemonchiffon"): CssIdentLemonchiffon;
  export function getName(name: "lightblue"): CssIdentLightblue;
  export function getName(name: "lightcoral"): CssIdentLightcoral;
  export function getName(name: "lightcyan"): CssIdentLightcyan;
  export function getName(name: "lightgray"): CssIdentLightgray;
  export function getName(name: "lightgreen"): CssIdentLightgreen;
  export function getName(name: "lightgrey"): CssIdentLightgrey;
  export function getName(name: "lightpink"): CssIdentLightpink;
  export function getName(name: "lightsalmon"): CssIdentLightsalmon;
  export function getName(name: "lightseagreen"): CssIdentLightseagreen;
  export function getName(name: "lightskyblue"): CssIdentLightskyblue;
  export function getName(name: "lightslategray"): CssIdentLightslategray;
  export function getName(name: "lightslategrey"): CssIdentLightslategrey;
  export function getName(name: "lightsteelblue"): CssIdentLightsteelblue;
  export function getName(name: "lightyellow"): CssIdentLightyellow;
  export function getName(name: "lime"): CssIdentLime;
  export function getName(name: "limegreen"): CssIdentLimegreen;
  export function getName(name: "linen"): CssIdentLinen;
  export function getName(name: "magenta"): CssIdentMagenta;
  export function getName(name: "maroon"): CssIdentMaroon;
  export function getName(name: "mediumaquamarine"): CssIdentMediumaquamarine;
  export function getName(name: "mediumblue"): CssIdentMediumblue;
  export function getName(name: "mediumorchid"): CssIdentMediumorchid;
  export function getName(name: "mediumpurple"): CssIdentMediumpurple;
  export function getName(name: "mediumseagreen"): CssIdentMediumseagreen;
  export function getName(name: "mediumslateblue"): CssIdentMediumslateblue;
  export function getName(name: "mediumspringgreen"): CssIdentMediumspringgreen;
  export function getName(name: "mediumturquoise"): CssIdentMediumturquoise;
  export function getName(name: "mediumvioletred"): CssIdentMediumvioletred;
  export function getName(name: "midnightblue"): CssIdentMidnightblue;
  export function getName(name: "mintcream"): CssIdentMintcream;
  export function getName(name: "mistyrose"): CssIdentMistyrose;
  export function getName(name: "moccasin"): CssIdentMoccasin;
  export function getName(name: "navajowhite"): CssIdentNavajowhite;
  export function getName(name: "navy"): CssIdentNavy;
  export function getName(name: "oldlace"): CssIdentOldlace;
  export function getName(name: "olive"): CssIdentOlive;
  export function getName(name: "olivedrab"): CssIdentOlivedrab;
  export function getName(name: "orange"): CssIdentOrange;
  export function getName(name: "orangered"): CssIdentOrangered;
  export function getName(name: "orchid"): CssIdentOrchid;
  export function getName(name: "palegoldenrod"): CssIdentPalegoldenrod;
  export function getName(name: "palegreen"): CssIdentPalegreen;
  export function getName(name: "paleturquoise"): CssIdentPaleturquoise;
  export function getName(name: "palevioletred"): CssIdentPalevioletred;
  export function getName(name: "papayawhip"): CssIdentPapayawhip;
  export function getName(name: "peachpuff"): CssIdentPeachpuff;
  export function getName(name: "peru"): CssIdentPeru;
  export function getName(name: "pink"): CssIdentPink;
  export function getName(name: "plum"): CssIdentPlum;
  export function getName(name: "powderblue"): CssIdentPowderblue;
  export function getName(name: "purple"): CssIdentPurple;
  export function getName(name: "rebeccapurple"): CssIdentRebeccapurple;
  export function getName(name: "red"): CssIdentRed;
  export function getName(name: "rosybrown"): CssIdentRosybrown;
  export function getName(name: "royalblue"): CssIdentRoyalblue;
  export function getName(name: "saddlebrown"): CssIdentSaddlebrown;
  export function getName(name: "salmon"): CssIdentSalmon;
  export function getName(name: "sandybrown"): CssIdentSandybrown;
  export function getName(name: "seagreen"): CssIdentSeagreen;
  export function getName(name: "seashell"): CssIdentSeashell;
  export function getName(name: "sienna"): CssIdentSienna;
  export function getName(name: "silver"): CssIdentSilver;
  export function getName(name: "skyblue"): CssIdentSkyblue;
  export function getName(name: "slateblue"): CssIdentSlateblue;
  export function getName(name: "slategray"): CssIdentSlategray;
  export function getName(name: "slategrey"): CssIdentSlategrey;
  export function getName(name: "snow"): CssIdentSnow;
  export function getName(name: "springgreen"): CssIdentSpringgreen;
  export function getName(name: "steelblue"): CssIdentSteelblue;
  export function getName(name: "tan"): CssIdentTan;
  export function getName(name: "teal"): CssIdentTeal;
  export function getName(name: "thistle"): CssIdentThistle;
  export function getName(name: "tomato"): CssIdentTomato;
  export function getName(name: "turquoise"): CssIdentTurquoise;
  export function getName(name: "violet"): CssIdentViolet;
  export function getName(name: "wheat"): CssIdentWheat;
  export function getName(name: "white"): CssIdentWhite;
  export function getName(name: "whitesmoke"): CssIdentWhitesmoke;
  export function getName(name: "yellow"): CssIdentYellow;
  export function getName(name: "yellowgreen"): CssIdentYellowgreen;
  export function getName(name: `--${string}`): DashedIdent;
}
